// <auto-generated />
namespace Keyframe.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AnimRequstUpdt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AnimRequstUpdt));
        
        string IMigrationMetadata.Id
        {
            get { return "202202172329014_AnimRequstUpdt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
